apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: greeting
spec:
  schedule: ""
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: main
            image: alpine:latest
            command: ["echo"]
            args: ["This is template."]
